name: My all new workflow

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Print welcome message
              run: echo "Welcome to the new strange thing"

            - name: List the files
              run: ls

            - name: Read file
              run: cat iron-man.txt